#!/bin/env python2

"""
Copyright 2014,2015 Louis-Guillaume Gagnon

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published
by the Free Software Foundation, either version 3 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import argparse, subprocess, sys, time

def getArgs():
    p = argparse.ArgumentParser()
    p.add_argument("-m", "--minutes", type=int, default=25)
    p.add_argument("-c", "--command", type=str, default="xterm -e cmatrix >/dev/null")
    return p.parse_args()

def pad(n):
    if n < 10:
        return "0%d" % n
    else:
        return "%d" % n

def p_timer(minutes):

    seconds = 0

    while minutes >= 0:
        subprocess.call(["clear"])
        subprocess.call(["figlet","-W","%s:%s" % (pad(minutes),pad(seconds))])
        if seconds == 0:
            seconds = 59
            minutes -= 1
        else:
            seconds -= 1
            time.sleep(1)

def main():
    args = getArgs()
    p_timer(args.minutes)
    subprocess.call(args.command, shell=True)
    return 0

if __name__ == '__main__':
    exit(main())
